# Site settings
title: Visual Analytic Project
author: Zhang xiang
  name: Zhang xiang
  email: zhangxiang1121@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
theme: minima
