# Site settings
title: Visual Analytic Project
author:Zhang Xiang
  name: Zhang Xiang
  email: zhangxiang1121@gmail.com
description: "Visual Analytic Project."

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
